// Package problem provides the canonical RFC 9457 ("Problem Details for HTTP
// APIs") error body shared by every tdp-apis resource service.
//
// Discovered by codegen-agent (TDP-9983) during the discover pass: all 16
// tdp-apis/*/api/docs/swagger.yaml resource specs independently define an
// identical `problem.ProblemDetails` schema (same four/five fields, same
// semantics) with no shared Go type backing it. This package is the first
// promotion of that recurring schema into tdp-shared-go, per the codegen
// pipeline's stage-5 shared-type-reuse-check (hard rule #4): the first
// resource client generated against a schema that recurs across specs
// promotes it here; every subsequent resource's generated client imports
// this type instead of regenerating an equivalent one.
//
// First consumer: tdp-apis/domain's GET /api/domains/{id_or_name} (get_domain)
// walking-skeleton codegen pass (TDP-9982/TDP-9983/TDP-9987).
package problem

import (
	"encoding/json"
	"maps"
	"net/http"
)

// MediaType is the IANA-registered media type for RFC 9457 Problem Details
// responses (RFC 9457 section 3). Servers writing a Details body MUST send
// this as the response's Content-Type.
const MediaType = "application/problem+json"

// Details is the RFC 9457 Problem Details error body. Field names and
// semantics match the `problem.ProblemDetails` definition duplicated across
// every tdp-apis resource swagger.yaml (see tdp-apis/domain/api/docs/swagger.yaml
// #/definitions/problem.ProblemDetails as the reference instance used to derive
// this shape).
type Details struct {
	// Type is a URI reference identifying the problem type. Optional; when
	// absent, "about:blank" is the RFC 9457 default.
	Type string `json:"type,omitempty"`

	// Title is a short, human-readable summary of the problem type.
	Title string `json:"title,omitempty"`

	// Status is the HTTP status code generated by the origin server for
	// this occurrence of the problem.
	Status int `json:"status,omitempty"`

	// Detail is a human-readable explanation specific to this occurrence
	// of the problem.
	Detail string `json:"detail,omitempty"`

	// Instance is a URI reference identifying the specific occurrence of
	// the problem.
	Instance string `json:"instance,omitempty"`

	// Extensions holds problem-type-specific members beyond the five
	// registered ones (RFC 9457 section 3.2, "Extension Members"). They are
	// serialized as sibling members of the JSON object, not nested under a
	// container key, and are round-tripped on unmarshal so a value passed
	// through unmodified doesn't silently drop members it doesn't recognize.
	Extensions map[string]any `json:"-"`
}

// Error implements the error interface so Details can be returned/wrapped
// as a normal Go error by generated clients.
func (d Details) Error() string {
	if d.Detail != "" {
		return d.Detail
	}
	if d.Title != "" {
		return d.Title
	}
	return "problem details error"
}

// MarshalJSON flattens Extensions alongside the five registered members.
func (d Details) MarshalJSON() ([]byte, error) {
	m := make(map[string]any, len(d.Extensions)+5)
	maps.Copy(m, d.Extensions)
	if d.Type != "" {
		m["type"] = d.Type
	}
	if d.Title != "" {
		m["title"] = d.Title
	}
	if d.Status != 0 {
		m["status"] = d.Status
	}
	if d.Detail != "" {
		m["detail"] = d.Detail
	}
	if d.Instance != "" {
		m["instance"] = d.Instance
	}
	return json.Marshal(m)
}

// UnmarshalJSON reads the five registered members into their fields and
// preserves any other members in Extensions.
func (d *Details) UnmarshalJSON(data []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	type fixed struct {
		Type     string `json:"type,omitempty"`
		Title    string `json:"title,omitempty"`
		Status   int    `json:"status,omitempty"`
		Detail   string `json:"detail,omitempty"`
		Instance string `json:"instance,omitempty"`
	}
	var f fixed
	if err := json.Unmarshal(data, &f); err != nil {
		return err
	}

	d.Type = f.Type
	d.Title = f.Title
	d.Status = f.Status
	d.Detail = f.Detail
	d.Instance = f.Instance

	for _, k := range [...]string{"type", "title", "status", "detail", "instance"} {
		delete(raw, k)
	}
	d.Extensions = nil
	if len(raw) > 0 {
		d.Extensions = raw
	}
	return nil
}

// WriteTo writes d as an RFC 9457 response: the MediaType Content-Type, the
// status line taken from d.Status (defaulting to 500 if unset), and the JSON
// body. It only depends on the standard library's http.ResponseWriter, so it
// works unmodified with gin, chi, or plain net/http handlers.
func (d Details) WriteTo(w http.ResponseWriter) error {
	status := d.Status
	if status == 0 {
		status = http.StatusInternalServerError
	}
	w.Header().Set("Content-Type", MediaType)
	w.WriteHeader(status)
	return json.NewEncoder(w).Encode(d)
}
