// Package problem provides the canonical RFC 9457 ("Problem Details for HTTP
// APIs") error body shared by every tdp-apis resource service.
//
// Discovered by codegen-agent (TDP-9983) during the discover pass: all 16
// tdp-apis/*/api/docs/swagger.yaml resource specs independently define an
// identical `problem.ProblemDetails` schema (same four/five fields, same
// semantics) with no shared Go type backing it. This package is the first
// promotion of that recurring schema into tdp-shared-go, per the codegen
// pipeline's stage-5 shared-type-reuse-check (hard rule #4): the first
// resource client generated against a schema that recurs across specs
// promotes it here; every subsequent resource's generated client imports
// this type instead of regenerating an equivalent one.
//
// First consumer: tdp-apis/domain's GET /api/domains/{id_or_name} (get_domain)
// walking-skeleton codegen pass (TDP-9982/TDP-9983/TDP-9987).
package problem

// Details is the RFC 9457 Problem Details error body. Field names and
// semantics match the `problem.ProblemDetails` definition duplicated across
// every tdp-apis resource swagger.yaml (see tdp-apis/domain/api/docs/swagger.yaml
// #/definitions/problem.ProblemDetails as the reference instance used to derive
// this shape).
type Details struct {
	// Type is a URI reference identifying the problem type. Optional; when
	// absent, "about:blank" is the RFC 9457 default.
	Type string `json:"type,omitempty"`

	// Title is a short, human-readable summary of the problem type.
	Title string `json:"title,omitempty"`

	// Status is the HTTP status code generated by the origin server for
	// this occurrence of the problem.
	Status int `json:"status,omitempty"`

	// Detail is a human-readable explanation specific to this occurrence
	// of the problem.
	Detail string `json:"detail,omitempty"`

	// Instance is a URI reference identifying the specific occurrence of
	// the problem.
	Instance string `json:"instance,omitempty"`
}

// Error implements the error interface so Details can be returned/wrapped
// as a normal Go error by generated clients.
func (d Details) Error() string {
	if d.Detail != "" {
		return d.Detail
	}
	if d.Title != "" {
		return d.Title
	}
	return "problem details error"
}
